# Example docker-compose file for TimeTagger that uses the published
# Docker image in the default root variant.
# Shows all options settable via the environment.
#
# !! Make sure to apply your own credentials                       !!
# !! You can use e.g. https://timetagger.app/cred to generate them !!
# !! In docker-compose characters '$' should be escaped as '$$'    !!
# !! If you use a .env file, use single quotes instead of escaping !!

services:
  timetagger:
    container_name: timetagger
    restart: always
    image: ghcr.io/almarklein/timetagger
    ports:
      - "8000:80"
    volumes:
      - ${HOME}/_timetagger:/root/_timetagger
    environment:
      - TIMETAGGER_BIND=0.0.0.0:80
      - TIMETAGGER_DATADIR=/root/_timetagger
      - TIMETAGGER_LOG_LEVEL=info
      - TIMETAGGER_CREDENTIALS=molly:$$2a$$08$$048Hi79IL/gyw0sLHEOk/OV1/a0uFM3KYTGlGS.Gukxa22IrCauQK # molly:4905aAbB
